services:
  web:
    build: ./app
    # command: bash -c 'python manage.py runserver 0.0.0.0:8000' # ; python manage.py start_zulip_listener'
#    entrypoint: ["/bin/sh", "-c"]
#    command: >
#      bash -c "python manage.py start_zulip_listener ; python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
    expose:
      - 8000
    environment:
      - DJANGO_ALLOWED_HOSTS=django.localhost
      - DEBUG=1
    #  - DATABASE_URL=postgresql://django_traefik:django_traefik@db:5432/django_traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django_traefik
      - POSTGRES_PASSWORD=django_traefik
      - POSTGRES_DB=django_traefik
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  traefik:
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      #- "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
