# Generated by Django 4.1.6 on 2025-07-12 19:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая компания', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('tg_id', models.IntegerField()),
                ('zulip_channel_id', models.IntegerField(default=0)),
                ('last_msg_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('staff', 'Сотрудник'), ('client', 'Клиент'), ('anonim', 'Аноним'), ('admin', 'Админ')], default='client', max_length=10)),
                ('pin_code', models.IntegerField(default=0)),
                ('activated', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.company')),
            ],
        ),
    ]
